// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using lt_core_persistence;

#nullable disable

namespace lt_core_api.Migrations
{
    [DbContext(typeof(LTCoreDbContext))]
    [Migration("20220702131630_added subtitle to learning path metadata")]
    partial class addedsubtitletolearningpathmetadata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("lt_core_persistence.Models.LearningPathMetaData", b =>
                {
                    b.Property<int>("LPId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LPId"));

                    b.Property<int>("CommentCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DownVotes")
                        .HasColumnType("integer");

                    b.Property<string>("LPCode")
                        .HasColumnType("text");

                    b.Property<string>("SubTitle")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int>("UpVotes")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("LPId");

                    b.ToTable("LearningPathMetaData");
                });

            modelBuilder.Entity("lt_core_persistence.Models.Topic", b =>
                {
                    b.Property<int>("TopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TopicId"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TopicName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TopicId");

                    b.HasIndex("TopicName")
                        .IsUnique();

                    b.ToTable("Topic");
                });

            modelBuilder.Entity("lt_core_persistence.Models.UserActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("InterestSet")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<string>("KcUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastActiveSessionId")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastLoggedIn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("KcUserId")
                        .IsUnique();

                    b.ToTable("UserActivity");
                });

            modelBuilder.Entity("lt_core_persistence.Models.UserTopic", b =>
                {
                    b.Property<int>("UserTopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserTopicId"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TopicId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("UserTopicId");

                    b.HasIndex("UserId");

                    b.HasIndex("TopicId", "UserId")
                        .IsUnique();

                    b.ToTable("UserTopic");
                });

            modelBuilder.Entity("lt_core_persistence.Models.UserTopic", b =>
                {
                    b.HasOne("lt_core_persistence.Models.Topic", "Topic")
                        .WithMany("UserTopic")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lt_core_persistence.Models.UserActivity", "UserActivity")
                        .WithMany("UserTopic")
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("KcUserId");

                    b.Navigation("Topic");

                    b.Navigation("UserActivity");
                });

            modelBuilder.Entity("lt_core_persistence.Models.Topic", b =>
                {
                    b.Navigation("UserTopic");
                });

            modelBuilder.Entity("lt_core_persistence.Models.UserActivity", b =>
                {
                    b.Navigation("UserTopic");
                });
#pragma warning restore 612, 618
        }
    }
}
