// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using lt_core_infrastructure;

#nullable disable

namespace lt_core_api.Migrations
{
    [DbContext(typeof(LTCoreDbContext))]
    partial class LTCoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("lt_core_infrastructure.Models.LearningPath", b =>
                {
                    b.Property<int>("LPId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LPId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("LPCode")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("LPId");

                    b.ToTable("LearningPaths");
                });
#pragma warning restore 612, 618
        }
    }
}
