services:
        postgres_db:
                build:
                        context: .
                        dockerfile: postgresDockerfile
                container_name: postgres_ubuntu_14
                restart: always
                environment:
                        POSTGRES_USER: root
                        POSTGRES_PASSWORD: root
                        POSTGRES_DB: postgres
                ports: ["5432:5432"]
                volumes:
                        - ./pgdata:/var/lib/postgresql/data
                        - ./pgconfig/postgresql:/etc/postgresql
        postgres_pgadmin:
                container_name: pgadmin4_new
                image: dpage/pgadmin4
                restart: always
                environment:
                        PGADMIN_DEFAULT_EMAIL: admin@admin.com
                        PGADMIN_DEFAULT_PASSWORD: root
                ports: ["5050:80"]
        masstransit_rabbitmq:
                container_name: mt_rabbitmq
                image: masstransit/rabbitmq
                restart: always
                ports:
                        - "15673:15672"
                        - "5673:5672"
     
