INSERT INTO public."Topic"("TopicName", "CreatedOn") VALUES 
('Computational geometry', clock_timestamp()),
('Distributed algorithms', clock_timestamp()),
('Parallel algorithms', clock_timestamp()),
('Randomized algorithms', clock_timestamp()),
('Business management', clock_timestamp()),
('Business law', clock_timestamp()),
('Business ethics', clock_timestamp()),
('Business analysis', clock_timestamp()),
('Business administration', clock_timestamp()),
('Acoustics', clock_timestamp()),
('Astrophysics', clock_timestamp()),
('Applied physics', clock_timestamp()),
('Aerodynamics', clock_timestamp()),
('Newtonian dynamics', clock_timestamp()),
('Molecular physics', clock_timestamp()),
('Electromagnetism', clock_timestamp()),
('Elementary particle physics', clock_timestamp()),
('Experimental physics', clock_timestamp()),
('Fluid dynamics', clock_timestamp()),
('Geophysics', clock_timestamp()),
('Mathematical physics', clock_timestamp()),
('Mechanics', clock_timestamp()),
('Medical physics', clock_timestamp()),
('Statistical mechanics', clock_timestamp()),
('Theoretical physics', clock_timestamp()),
('Thermal physics', clock_timestamp()),
('Thermodynamics', clock_timestamp());